services:
  # 全栈应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # 改为 8080 避免与 Dokploy 冲突
      - "9091:9091"
    volumes:
      # 挂载临时文件目录
      - ./temp:/app/temp
    environment:
      - NODE_ENV=production
      - PORT=9091
    restart: unless-stopped
    # 添加资源限制和文件描述符限制
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9091/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s