services:
  # 后端API服务
  api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "9091:9091"
    volumes:
      # 挂载临时文件目录
      - ./temp:/app/temp
    environment:
      - NODE_ENV=production
      - PORT=9091
      - CHOKIDAR_USEPOLLING=false
      - WATCHPACK_POLLING=false
    restart: unless-stopped
    # 资源限制和文件描述符优化
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9091/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # 网络配置
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge