services:
  # 全栈应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "9091:9091"
    volumes:
      # 挂载临时文件目录
      - ./temp:/app/temp
    environment:
      - NODE_ENV=production
      - PORT=9091
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9091/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s