#!/bin/bash

clear
echo "📱 手机DNS配置详细指南"
echo "======================"
echo ""

LOCAL_IP=$(hostname -I | awk '{print $1}')
echo "🎯 目标: 将手机DNS设置为 $LOCAL_IP"
echo "🎪 效果: 手机可以访问 http://labubu.local:3000"
echo ""

echo "📱 Android手机配置步骤"
echo "===================="
echo ""
echo "方法1: WiFi高级设置 (推荐)"
echo "------------------------"
echo "1. 📶 打开手机【设置】"
echo "2. 🌐 点击【WiFi】或【无线和网络】"
echo "3. 📡 找到当前连接的WiFi网络"
echo "4. 🔧 长按WiFi名称，选择【修改网络】或【网络详情】"
echo "5. ⚙️  点击【高级选项】或【高级设置】"
echo "6. 🔄 将【IP设置】改为【静态】"
echo "7. 🌐 找到【DNS 1】或【首选DNS】"
echo "8. ✏️  输入: $LOCAL_IP"
echo "9. 💾 点击【保存】"
echo "10. 🔄 断开WiFi重新连接"
echo ""

echo "方法2: 网络设置 (部分Android)"
echo "---------------------------"
echo "1. 📶 打开【设置】→【连接】→【WiFi】"
echo "2. ⚙️  点击WiFi名称旁的【齿轮图标】"
echo "3. 📝 点击【编辑】或【修改】"
echo "4. 🔧 展开【高级选项】"
echo "5. 🌐 将【IP设置】改为【静态】"
echo "6. 📝 在【DNS 1】中输入: $LOCAL_IP"
echo "7. 💾 保存并重新连接"
echo ""

echo "📱 iPhone配置步骤"
echo "================"
echo ""
echo "1. ⚙️  打开【设置】"
echo "2. 📶 点击【WiFi】"
echo "3. ℹ️  点击当前WiFi网络旁的【ℹ️】图标"
echo "4. 🌐 点击【配置DNS】"
echo "5. 📝 选择【手动】"
echo "6. ➕ 点击【添加服务器】"
echo "7. ✏️  输入: $LOCAL_IP"
echo "8. 💾 点击【存储】"
echo "9. 🔄 关闭WiFi再重新连接"
echo ""

echo "🔧 详细图解说明"
echo "=============="
echo ""
echo "Android详细步骤:"
echo "---------------"
echo "设置 → WiFi → [点击已连接的WiFi] → 修改网络"
echo "↓"
echo "高级选项 → IP设置: 静态"
echo "↓"  
echo "DNS 1: $LOCAL_IP"
echo "↓"
echo "保存 → 重新连接WiFi"
echo ""

echo "iPhone详细步骤:"
echo "--------------"
echo "设置 → WiFi → [点击WiFi旁的ℹ️] → 配置DNS"
echo "↓"
echo "手动 → 添加服务器"
echo "↓"
echo "输入: $LOCAL_IP"
echo "↓"
echo "存储 → 重新连接WiFi"
echo ""

echo "🧪 配置完成后测试"
echo "================"
echo "1. 📱 打开手机浏览器"
echo "2. 🌐 输入: http://labubu.local:3000"
echo "3. 🎉 如果能打开，说明配置成功！"
echo ""

echo "❌ 如果无法访问，尝试以下地址:"
echo "  • http://labubu-gallery.local:3000"
echo "  • http://wallpaper.local:3000"
echo "  • http://$LOCAL_IP:3000 (IP访问)"
echo ""

echo "🔧 故障排除"
echo "=========="
echo ""
echo "问题1: 找不到DNS设置"
echo "-------------------"
echo "• 不同手机品牌界面略有差异"
echo "• 寻找关键词: DNS、域名服务器、网络设置"
echo "• 有些手机在【连接】→【更多连接设置】中"
echo ""

echo "问题2: 没有静态IP选项"
echo "-------------------"
echo "• 尝试寻找【IP设置】或【DHCP】选项"
echo "• 将DHCP改为静态或手动"
echo "• 部分手机可能不支持修改DNS"
echo ""

echo "问题3: 配置后仍无法访问"
echo "-------------------"
echo "• 检查输入的IP是否正确: $LOCAL_IP"
echo "• 尝试重启手机WiFi"
echo "• 检查手机和电脑是否在同一网络"
echo "• 使用IP地址访问: http://$LOCAL_IP:3000"
echo ""

echo "📋 不同品牌手机的具体路径"
echo "======================"
echo ""
echo "🔸 华为/荣耀:"
echo "   设置 → WLAN → 长按WiFi → 修改网络 → 显示高级选项"
echo ""
echo "🔸 小米/红米:"
echo "   设置 → WLAN → 点击WiFi → IP设置 → 静态"
echo ""
echo "🔸 OPPO/一加:"
echo "   设置 → WiFi → 点击WiFi → IP设置 → 静态"
echo ""
echo "🔸 vivo:"
echo "   设置 → WLAN → 点击WiFi → IP设置 → 静态"
echo ""
echo "🔸 三星:"
echo "   设置 → 连接 → WiFi → 点击WiFi → 高级 → IP设置"
echo ""

echo "💡 替代方案"
echo "=========="
echo ""
echo "方案1: 使用DNS修改应用 (需要root)"
echo "--------------------------------"
echo "• Android: DNS Changer、1.1.1.1等应用"
echo "• 可以全局修改DNS设置"
echo ""

echo "方案2: 路由器DNS设置 (推荐)"
echo "-------------------------"
echo "• 电脑浏览器访问: http://172.27.0.1"
echo "• 登录路由器管理界面"
echo "• 添加静态DNS条目: labubu.local → $LOCAL_IP"
echo "• 所有设备自动生效，无需单独配置"
echo ""

echo "方案3: 继续使用IP访问"
echo "-------------------"
echo "• 如果DNS配置困难，直接使用IP访问"
echo "• 地址: http://$LOCAL_IP:3000"
echo "• 功能完全相同，只是地址不够友好"
echo ""

echo "🎯 配置成功的标志"
echo "================"
echo "✅ 手机浏览器能访问: http://labubu.local:3000"
echo "✅ 显示Labubu壁纸画廊主页"
echo "✅ 图片能正常加载"
echo "✅ 分享功能正常工作"
echo ""

echo "📞 需要帮助?"
echo "==========="
echo "如果按照步骤仍无法配置，可能的原因:"
echo "• 手机系统版本较老，不支持DNS修改"
echo "• 运营商或网络限制"
echo "• 路由器设置问题"
echo ""
echo "建议: 优先尝试路由器DNS配置，一次设置全网生效！"
